import os
import xml.etree.ElementTree as ET
from xml.dom import minidom

def generate_wsp_file(base_directory, output_file):
    """
    Searches for .c and .h files in 'src' and 'header' subdirectories,
    creates corresponding folders if they don't exist, and generates a .wsp file
    listing the found files.

    Args:
        base_directory (str): The directory where the script is located.
        output_file (str): The full path to the output .wsp file.
    """

    src_files = []
    header_files = []

    src_dir = os.path.join(base_directory, "src")
    header_dir = os.path.join(base_directory, "include")

    # Create directories if they don't exist
    os.makedirs(src_dir, exist_ok=True)
    os.makedirs(header_dir, exist_ok=True)

    # Scan for .c files in the src subdirectory
    if os.path.exists(src_dir):
        for file in os.listdir(src_dir):
            if file.endswith(".c"):
                src_files.append(os.path.join("src", file))

    # Scan for .h files in the header subdirectory
    if os.path.exists(header_dir):
        for file in os.listdir(header_dir):
            if file.endswith(".h"):
                header_files.append(os.path.join("include", file))

    # Create XML structure
    notepad_plus = ET.Element("NotepadPlus")
    project = ET.SubElement(notepad_plus, "Project", name="AutoGeneratedProject")

    if src_files:
        folder_src = ET.SubElement(project, "Folder", name="src")
        for f in sorted(src_files):
            ET.SubElement(folder_src, "File", name=f)

    if header_files:
        folder_header = ET.SubElement(project, "Folder", name="include")
        for h in sorted(header_files):
            ET.SubElement(folder_header, "File", name=h)

    # Write to a string first
    tree = ET.ElementTree(notepad_plus)
    xml_str = ET.tostring(notepad_plus, encoding="utf-8", method="xml").decode("utf-8")

    # Use minidom to format the string with indentation
    xml_str = minidom.parseString(xml_str).toprettyxml(indent="    ")

    # Write to the file with CRLF line endings and indentation
    with open(output_file, "w", newline='\r\n') as f:
        f.write(xml_str)

    print(f"WSP file generated: {output_file}")

if __name__ == "__main__":
    directory = os.path.dirname(os.path.abspath(__file__))  # Current folder

    while True:
        output_name = input("Enter the name for the output .wsp file (without extension): ")
        output_filename = f"{output_name}"
        # output_filename = f"{output_name}.wsp"
        output_path = os.path.join(directory, output_filename)

        if os.path.exists(output_path):
            print(f"File '{output_filename}' already exists. Please enter a different name.")
        else:
            break

    generate_wsp_file(directory, output_path)